# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

# =============================================================================
# AWS-GITLAB-RUNNER-WINDOWS
# =============================================================================

  aws-gitlab-runner-windows:
    container_name: ${CONTAINER_NAME}
    env_file: ./.env
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    networks:
      - aws-gitlab-runner-windows

# =============================================================================
# NETWORK
# =============================================================================

networks:
  aws-gitlab-runner-windows:
